apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      name: keycloak
      port: 9696
      targetPort: 8080
  type: LoadBalancer
