version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:alpine3.17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGPORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - order-net

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5433/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    command:
      - "start-dev"
    ports:
      - '9696:8080'
    networks:
      - order-net

volumes:
  postgres-data:

networks:
  order-net:
    driver: bridge