apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:alpine3.17
          ports:
            - containerPort: 5433
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: db_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: db_password
          envFrom:
            - configMapRef:
                name: postgres-config