apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      name: postgres
      port: 5433
      targetPort: 5433
  type: LoadBalancer
