apiVersion: v1
kind: ConfigMap
metadata:
  name: order-be-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5433/order_db"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak:9696/realms/order-service"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:9696/realms/order-service/protocol/openid-connect/certs"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "guest"
  SPRING_RABBITMQ_PASSWORD: "guest"
